<a href="https://colab.research.google.com/github/michael-0007a/II-II_AD-repo/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6,7,8,9,10],[2,12,23,10,89]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 2, 12, 23, 10, 89]])

In [ ]:
arr[2,4]

89

In [ ]:
arr = np.array([[[1, 2, 3,],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
arr[1,1,2]

12

In [ ]:
arr[0,1,2]

6

In [ ]:
import pandas as pd

patient_data = {
    'Patient Name': ['Michael', 'Rithik', 'Harsha', 'Deepak'],
    'Age': [5, 32, 6, 4],
    'Date of Appointment': ['2025-01-10', '2025-01-12', '2025-01-15', '2025-01-20'],
    'Patient ID': [1, 2, 3, 4]
}
patient_df = pd.DataFrame(patient_data)

print(patient_df)

  Patient Name  Age Date of Appointment  Patient ID
0      Michael    5          2025-01-10           1
1       Rithik   32          2025-01-12           2
2       Harsha    6          2025-01-15           3
3       Deepak    4          2025-01-20           4


In [ ]:

drug_quantity_data = {
    'Drug Name': ['Paracetamol', 'Ibuprofen', 'Amoxicillin', 'Cough Syrup'],
    'Quantity': [2, 1, 3, 1],
    'Patient ID': [1, 2, 3, 4]
}
drug_quantity_df = pd.DataFrame(drug_quantity_data)

print(drug_quantity_df)

     Drug Name  Quantity  Patient ID
0  Paracetamol         2           1
1    Ibuprofen         1           2
2  Amoxicillin         3           3
3  Cough Syrup         1           4


In [ ]:
# patients with Age < 6
filtered_patients = patient_df.loc[patient_df['Age'] < 6, ['Patient Name', 'Age']]


print("\nFiltered Patients (Age < 6):")
print(filtered_patients)


Filtered Patients (Age < 6):
  Patient Name  Age
0      Michael    5
3       Deepak    4


In [ ]:
merged_df = pd.merge(patient_df, drug_quantity_df, on='Patient ID', how='inner')

print("\nMerged DataFrame:")
print(merged_df)


Merged DataFrame:
  Patient Name  Age Date of Appointment  Patient ID    Drug Name  Quantity
0      Michael    5          2025-01-10           1  Paracetamol         2
1       Rithik   32          2025-01-12           2    Ibuprofen         1
2       Harsha    6          2025-01-15           3  Amoxicillin         3
3       Deepak    4          2025-01-20           4  Cough Syrup         1


In [23]:
merged_df

Patient Name  Age Date of Appointment  Patient ID    Drug Name  Quantity
0      Michael    5          2025-01-10           1  Paracetamol         2
1       Rithik   32          2025-01-12           2    Ibuprofen         1
2       Harsha    6          2025-01-15           3  Amoxicillin         3
3       Deepak    4          2025-01-20           4  Cough Syrup         1